// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelPlanner.Api.Infrastructure.Persistence;

#nullable disable

namespace TravelPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919235455_CorrectBjelasnicaRegion")]
    partial class CorrectBjelasnicaRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerNightKM")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Accommodation", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("BestSeasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("BestTimeToVisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BudgetTier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuggestedStayMaxDays")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedStayMinDays")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Destination", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000001"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "april-oktobar",
                            BudgetTier = "standard",
                            Description = "Grad koji je Isa-beg Isaković osnovao 1462. godine oko trgovačke čaršije, danas poznate kao Baščaršija — lavirint kaldrmisanih uličica, Sebilj fontane i Vijećnice čija je obnovljena kupola simbol grada. Sarajevo nosi tragove i osmanskog, i austrougarskog, i socijalističkog nasljeđa: od Latinske ćuprije gdje je počeo Prvi svjetski rat, preko olimpijskog duha 1984. godine, do Tunela spasa koji je grad održao u životu tokom opsade. Uz sve to, čaršijska kafa, ćevapi i burek čine Sarajevo gradom koji se jednako doživljava svim čulima.",
                            Name = "Sarajevo",
                            Region = "Centralna Bosna",
                            SuggestedStayMaxDays = 4,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "historija", "kultura", "grad", "hrana" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000002"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "maj-septembar",
                            BudgetTier = "standard",
                            Description = "Simbol grada je Stari most — remek-djelo osmanskog graditelja Mimara Hajrudina iz 1566. godine, srušeno u ratu 1993. i vjerno obnovljeno 2004, danas pod zaštitom UNESCO-a. Mladići koji skaču sa 24 metra visokog mosta u hladnu Neretvu nastavljaju tradiciju staru nekoliko stoljeća. Stara čaršija oko mosta, sa zanatskim radnjama i ćevabdžinicama, čuva duh grada koji je oduvijek bio raskršće kultura.",
                            Name = "Mostar",
                            Region = "Hercegovina",
                            SuggestedStayMaxDays = 3,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "historija", "kultura", "rijeka", "hrana" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000003"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "maj-oktobar",
                            BudgetTier = "standard",
                            Description = "Poznat kao \"grad sunca i platana\", Trebinje čuva Kastel — staru čaršiju iz 18. stoljeća — te Arslanagića most iz 16. stoljeća, zadužbinu velikog vezira Mehmed-paše Sokolovića. Iznad grada bdije manastir Hercegovačka Gračanica, a u obližnjem manastiru Tvrdoš i drugim podrumima uzgaja se žilavka, autohtona hercegovačka sorta grožđa poznata još od 14. stoljeća. Planina Leotar iznad grada nudi staze za planinarenje i pogled na cijelu dolinu Trebišnjice.",
                            Name = "Trebinje",
                            Region = "Hercegovina",
                            SuggestedStayMaxDays = 3,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "vino", "kultura", "rijeka", "grad" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000004"),
                            BestSeasons = new List<string> { "summer" },
                            BestTimeToVisit = "jun-septembar",
                            BudgetTier = "standard",
                            Description = "Jedini bh. izlaz na Jadransko more — svega oko 24 kilometra obale — čini Neum omiljenom destinacijom za porodični ljetni odmor. Hotelski resorti, plaže i restorani sa svježim morskim specijalitetima privlače posjetioce iz cijele regije, dok blizina Dubrovnika i Hercegovine čini Neum praktičnom bazom za dnevne izlete.",
                            Name = "Neum",
                            Region = "Hercegovina",
                            SuggestedStayMaxDays = 5,
                            SuggestedStayMinDays = 3,
                            Tags = new List<string> { "more", "porodica", "wellness" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000005"),
                            BestSeasons = new List<string> { "winter", "summer" },
                            BestTimeToVisit = "decembar-mart (zima), jun-septembar (planinarenje)",
                            BudgetTier = "premium",
                            Description = "Jahorina je bila domaćin ženskih alpskih disciplina na Zimskim olimpijskim igrama 1984. godine i od tada je najpoznatije skijalište u BiH, sa vrhom Ogorjelica na oko 1916 metara nadmorske visine. Van sezone skijanja, planina nudi staze za planinarenje i biciklizam okružene bukovom šumom, uz čist planinski vazduh svega pola sata vožnje od Sarajeva.",
                            Name = "Jahorina",
                            Region = "Istočno Sarajevo",
                            SuggestedStayMaxDays = 4,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "planina", "zima", "avantura" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000006"),
                            BestSeasons = new List<string> { "winter", "summer" },
                            BestTimeToVisit = "decembar-mart (zima), jun-septembar (planinarenje)",
                            BudgetTier = "standard",
                            Description = "Domaćin muških alpskih disciplina na Olimpijadi 1984, Bjelašnica danas spaja moderne skijaške staze sa autentičnim planinskim selom Lukomirom — najvišim i najizolovanijim naseljenim mjestom u BiH, gdje se i dalje čuvaju stari stećci i pastirski način života. Ljeti je planina omiljena među planinarima i biciklistima zbog netaknute prirode i pogleda na okolne vrhove.",
                            Name = "Bjelašnica",
                            Region = "Sarajevski kanton",
                            SuggestedStayMaxDays = 3,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "planina", "zima", "avantura", "priroda" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000007"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "april-oktobar",
                            BudgetTier = "budget",
                            Description = "Najveći grad Republike Srpske raste oko tvrđave Kastel na obali Vrbasa, čiji temelji sežu u rimsko i preosmansko doba, a današnji izgled poprima za vrijeme Ferhad-paše Sokolovića. Obnovljena Ferhadija džamija iz 16. stoljeća i katedrala Hrista Spasitelja svjedoče o vjerskoj raznolikosti grada, dok brze vode Vrbasa privlače kajakaše, raftere, pa i tradicionalne \"dajak\" čamce kojima se lokalci provlače kroz brzake. Kafanska kultura duž šetališta i brojni festivali daju gradu opušten, mladalački ritam.",
                            Name = "Banja Luka",
                            Region = "Republika Srpska",
                            SuggestedStayMaxDays = 3,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "grad", "kultura", "rijeka" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000008"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "maj-oktobar",
                            BudgetTier = "budget",
                            Description = "Travnik je gotovo 150 godina bio sjedište bosanskih vezira i prijestonica Osmanskog carstva u Bosni, s tvrđavom koja i danas dominira gradom. Rodno mjesto je nobelovca Ive Andrića, koji je grad ovjekovječio u romanu \"Travnička hronika\". Izvor Plava voda i okolna brda daju gradu poseban ambijent, a travnički sir, spravljen po staroj recepturi, jedan je od najpoznatijih bh. sireva.",
                            Name = "Travnik",
                            Region = "Centralna Bosna",
                            SuggestedStayMaxDays = 2,
                            SuggestedStayMinDays = 1,
                            Tags = new List<string> { "historija", "kultura", "planina" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000009"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "april-oktobar",
                            BudgetTier = "budget",
                            Description = "Počitelj je izuzetno dobro očuvano srednjovjekovno i osmansko naselje na strmoj obali Neretve, sa kamenom kulom, Hadži-Alijinom džamijom iz 16. stoljeća i uskim stepeništima koja se penju kroz staro jezgro. Od 1960-ih grad je poznat i kao umjetnička kolonija, koja mu je donijela dodatni sloj kulturnog života uz srednjovjekovnu arhitekturu.",
                            Name = "Počitelj",
                            Region = "Hercegovina",
                            SuggestedStayMaxDays = 2,
                            SuggestedStayMinDays = 1,
                            Tags = new List<string> { "historija", "kultura", "rijeka" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000010"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "maj-oktobar",
                            BudgetTier = "budget",
                            Description = "Višegrad je nosilac Mehmed-paša Sokolović mosta iz 1577. godine, remek-djela osmanske arhitekture pod zaštitom UNESCO-a, koji je Ivo Andrić ovjekovječio u romanu \"Na Drini ćuprija\" za koji je dobio Nobelovu nagradu. U blizini se nalazi i Andrićgrad, kamena gradska četvrt posvećena piščevom djelu, koju je podigao reditelj Emir Kusturica.",
                            Name = "Višegrad",
                            Region = "Istočna Bosna",
                            SuggestedStayMaxDays = 2,
                            SuggestedStayMinDays = 1,
                            Tags = new List<string> { "historija", "kultura", "rijeka" }
                        },
                        new
                        {
                            Id = new Guid("1a0a0001-0000-4000-8000-000000000011"),
                            BestSeasons = new List<string> { "spring", "summer", "autumn" },
                            BestTimeToVisit = "maj-oktobar",
                            BudgetTier = "standard",
                            Description = "Jajce je jedini grad na svijetu sa vodopadom usred samog centra — Pliva se sa oko 20 metara visine uliva u Vrbas, tik ispod srednjovjekovne tvrđave koja je nekad bila posljednje uporište nezavisnog Bosanskog kraljevstva. U gradu je 1943. održano drugo zasjedanje AVNOJ-a, kojim je postavljen temelj socijalističke Jugoslavije. Nekoliko kilometara uzvodno, stara vodenice na Plivskim jezerima (\"mlinčići\") dodatno svjedoče o dugoj istoriji ovog malog, ali slojevitog grada.",
                            Name = "Jajce",
                            Region = "Centralna Bosna",
                            SuggestedStayMaxDays = 3,
                            SuggestedStayMinDays = 2,
                            Tags = new List<string> { "historija", "priroda", "rijeka" }
                        });
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.DestinationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BestTimeToVisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("DestinationTranslation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000001"),
                            BestTimeToVisit = "april-oktobar",
                            Description = "Grad koji je Isa-beg Isaković osnovao 1462. godine oko trgovačke čaršije, danas poznate kao Baščaršija — lavirint kaldrmisanih uličica, Sebilj fontane i Vijećnice čija je obnovljena kupola simbol grada. Sarajevo nosi tragove i osmanskog, i austrougarskog, i socijalističkog nasljeđa: od Latinske ćuprije gdje je počeo Prvi svjetski rat, preko olimpijskog duha 1984. godine, do Tunela spasa koji je grad održao u životu tokom opsade. Uz sve to, čaršijska kafa, ćevapi i burek čine Sarajevo gradom koji se jednako doživljava svim čulima.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000001"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000002"),
                            BestTimeToVisit = "April-October",
                            Description = "Founded in 1462 by Isa-beg Isaković around a trading bazaar now known as Baščaršija — a maze of cobbled lanes, the Sebilj fountain, and the City Hall (Vijećnica) whose rebuilt dome has become a city symbol. Sarajevo carries layers of Ottoman, Austro-Hungarian, and socialist heritage: from the Latin Bridge where World War I began, through the Olympic spirit of 1984, to the Tunnel of Hope that kept the city alive during the siege. Strong coffee, ćevapi, and burek round out a city best experienced with every sense.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000001"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000003"),
                            BestTimeToVisit = "maj-septembar",
                            Description = "Simbol grada je Stari most — remek-djelo osmanskog graditelja Mimara Hajrudina iz 1566. godine, srušeno u ratu 1993. i vjerno obnovljeno 2004, danas pod zaštitom UNESCO-a. Mladići koji skaču sa 24 metra visokog mosta u hladnu Neretvu nastavljaju tradiciju staru nekoliko stoljeća. Stara čaršija oko mosta, sa zanatskim radnjama i ćevabdžinicama, čuva duh grada koji je oduvijek bio raskršće kultura.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000002"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000004"),
                            BestTimeToVisit = "May-September",
                            Description = "The city's symbol is Stari Most — a masterpiece built in 1566 by Ottoman architect Mimar Hajruddin, destroyed during the 1993 war and faithfully rebuilt in 2004, now a UNESCO World Heritage Site. Young divers leaping 24 meters into the cold Neretva below continue a tradition centuries old. The old bazaar surrounding the bridge, with its craft shops and grill restaurants, preserves the spirit of a city that has always stood at a crossroads of cultures.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000002"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000005"),
                            BestTimeToVisit = "maj-oktobar",
                            Description = "Poznat kao \"grad sunca i platana\", Trebinje čuva Kastel — staru čaršiju iz 18. stoljeća — te Arslanagića most iz 16. stoljeća, zadužbinu velikog vezira Mehmed-paše Sokolovića. Iznad grada bdije manastir Hercegovačka Gračanica, a u obližnjem manastiru Tvrdoš i drugim podrumima uzgaja se žilavka, autohtona hercegovačka sorta grožđa poznata još od 14. stoljeća. Planina Leotar iznad grada nudi staze za planinarenje i pogled na cijelu dolinu Trebišnjice.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000003"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000006"),
                            BestTimeToVisit = "May-October",
                            Description = "Known as \"the city of sun and plane trees,\" Trebinje preserves Kastel — its 18th-century old town — and the 16th-century Arslanagić Bridge, endowed by the grand vizier Mehmed-pasha Sokolović. The Hercegovačka Gračanica monastery watches over the city from above, while the nearby Tvrdoš monastery and local cellars produce žilavka, an indigenous Herzegovinian grape variety cultivated since the 14th century. Mount Leotar above town offers hiking trails and sweeping views of the Trebišnjica valley.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000003"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000007"),
                            BestTimeToVisit = "jun-septembar",
                            Description = "Jedini bh. izlaz na Jadransko more — svega oko 24 kilometra obale — čini Neum omiljenom destinacijom za porodični ljetni odmor. Hotelski resorti, plaže i restorani sa svježim morskim specijalitetima privlače posjetioce iz cijele regije, dok blizina Dubrovnika i Hercegovine čini Neum praktičnom bazom za dnevne izlete.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000004"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000008"),
                            BestTimeToVisit = "June-September",
                            Description = "Bosnia's only stretch of Adriatic coastline — roughly 24 kilometers — makes Neum a favorite for family summer holidays. Hotel resorts, beaches, and restaurants serving fresh seafood draw visitors from across the region, while its proximity to Dubrovnik and Herzegovina makes it a convenient base for day trips.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000004"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000009"),
                            BestTimeToVisit = "decembar-mart (zima), jun-septembar (planinarenje)",
                            Description = "Jahorina je bila domaćin ženskih alpskih disciplina na Zimskim olimpijskim igrama 1984. godine i od tada je najpoznatije skijalište u BiH, sa vrhom Ogorjelica na oko 1916 metara nadmorske visine. Van sezone skijanja, planina nudi staze za planinarenje i biciklizam okružene bukovom šumom, uz čist planinski vazduh svega pola sata vožnje od Sarajeva.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000005"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000010"),
                            BestTimeToVisit = "December-March (skiing), June-September (hiking)",
                            Description = "Jahorina hosted the women's alpine skiing events at the 1984 Winter Olympics and remains Bosnia's best-known ski resort, with its Ogorjelica peak reaching around 1,916 meters. Outside ski season, the mountain offers hiking and biking trails through beech forest, with clean mountain air just half an hour from Sarajevo.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000005"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000011"),
                            BestTimeToVisit = "decembar-mart (zima), jun-septembar (planinarenje)",
                            Description = "Domaćin muških alpskih disciplina na Olimpijadi 1984, Bjelašnica danas spaja moderne skijaške staze sa autentičnim planinskim selom Lukomirom — najvišim i najizolovanijim naseljenim mjestom u BiH, gdje se i dalje čuvaju stari stećci i pastirski način života. Ljeti je planina omiljena među planinarima i biciklistima zbog netaknute prirode i pogleda na okolne vrhove.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000006"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000012"),
                            BestTimeToVisit = "December-March (skiing), June-September (hiking)",
                            Description = "Host of the men's alpine skiing events at the 1984 Olympics, Bjelašnica today pairs modern ski slopes with the authentic mountain village of Lukomir — the highest and most isolated inhabited settlement in Bosnia, where medieval stećci tombstones and a traditional shepherding life endure. In summer the mountain draws hikers and cyclists for its untouched landscape and panoramic views.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000006"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000013"),
                            BestTimeToVisit = "april-oktobar",
                            Description = "Najveći grad Republike Srpske raste oko tvrđave Kastel na obali Vrbasa, čiji temelji sežu u rimsko i preosmansko doba, a današnji izgled poprima za vrijeme Ferhad-paše Sokolovića. Obnovljena Ferhadija džamija iz 16. stoljeća i katedrala Hrista Spasitelja svjedoče o vjerskoj raznolikosti grada, dok brze vode Vrbasa privlače kajakaše, raftere, pa i tradicionalne \"dajak\" čamce kojima se lokalci provlače kroz brzake. Kafanska kultura duž šetališta i brojni festivali daju gradu opušten, mladalački ritam.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000007"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000014"),
                            BestTimeToVisit = "April-October",
                            Description = "The largest city in Republika Srpska grew up around the Kastel fortress on the banks of the Vrbas, with roots reaching back to Roman and pre-Ottoman times and its present form shaped under Ferhad-pasha Sokolović. The rebuilt 16th-century Ferhadija Mosque and the Cathedral of Christ the Saviour reflect the city's religious diversity, while the fast-flowing Vrbas draws kayakers, rafters, and even traditional \"dajak\" pole-boats used by locals to navigate the rapids. A lively café culture along the riverside promenades and numerous festivals give the city a relaxed, youthful energy.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000007"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000015"),
                            BestTimeToVisit = "maj-oktobar",
                            Description = "Travnik je gotovo 150 godina bio sjedište bosanskih vezira i prijestonica Osmanskog carstva u Bosni, s tvrđavom koja i danas dominira gradom. Rodno mjesto je nobelovca Ive Andrića, koji je grad ovjekovječio u romanu \"Travnička hronika\". Izvor Plava voda i okolna brda daju gradu poseban ambijent, a travnički sir, spravljen po staroj recepturi, jedan je od najpoznatijih bh. sireva.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000008"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000016"),
                            BestTimeToVisit = "May-October",
                            Description = "For nearly 150 years, Travnik was the seat of Bosnia's Ottoman viziers and the province's capital, with a hilltop fortress that still dominates the town. It's the birthplace of Nobel laureate Ivo Andrić, who immortalized the town in his novel \"Bosnian Chronicle.\" The Plava Voda spring and surrounding hills give the town its distinctive charm, and Travnik cheese, made to an old recipe, is one of Bosnia's best-known cheeses.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000008"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000017"),
                            BestTimeToVisit = "april-oktobar",
                            Description = "Počitelj je izuzetno dobro očuvano srednjovjekovno i osmansko naselje na strmoj obali Neretve, sa kamenom kulom, Hadži-Alijinom džamijom iz 16. stoljeća i uskim stepeništima koja se penju kroz staro jezgro. Od 1960-ih grad je poznat i kao umjetnička kolonija, koja mu je donijela dodatni sloj kulturnog života uz srednjovjekovnu arhitekturu.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000009"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000018"),
                            BestTimeToVisit = "April-October",
                            Description = "Počitelj is an exceptionally well-preserved medieval and Ottoman-era settlement perched above the Neretva River, with a stone tower, the 16th-century Hadži-Alija Mosque, and narrow stepped lanes climbing through the old core. Since the 1960s the town has also been known as an artists' colony, adding a layer of living culture to its medieval architecture.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000009"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000019"),
                            BestTimeToVisit = "maj-oktobar",
                            Description = "Višegrad je nosilac Mehmed-paša Sokolović mosta iz 1577. godine, remek-djela osmanske arhitekture pod zaštitom UNESCO-a, koji je Ivo Andrić ovjekovječio u romanu \"Na Drini ćuprija\" za koji je dobio Nobelovu nagradu. U blizini se nalazi i Andrićgrad, kamena gradska četvrt posvećena piščevom djelu, koju je podigao reditelj Emir Kusturica.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000010"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000020"),
                            BestTimeToVisit = "May-October",
                            Description = "Višegrad is home to the 1577 Mehmed Paša Sokolović Bridge, a masterpiece of Ottoman architecture and a UNESCO World Heritage Site, immortalized by Ivo Andrić in his Nobel Prize-winning novel \"The Bridge on the Drina.\" Nearby stands Andrićgrad, a stone town quarter built by director Emir Kusturica in tribute to the writer's work.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000010"),
                            LanguageCode = "en"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000021"),
                            BestTimeToVisit = "maj-oktobar",
                            Description = "Jajce je jedini grad na svijetu sa vodopadom usred samog centra — Pliva se sa oko 20 metara visine uliva u Vrbas, tik ispod srednjovjekovne tvrđave koja je nekad bila posljednje uporište nezavisnog Bosanskog kraljevstva. U gradu je 1943. održano drugo zasjedanje AVNOJ-a, kojim je postavljen temelj socijalističke Jugoslavije. Nekoliko kilometara uzvodno, stara vodenice na Plivskim jezerima (\"mlinčići\") dodatno svjedoče o dugoj istoriji ovog malog, ali slojevitog grada.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000011"),
                            LanguageCode = "bs"
                        },
                        new
                        {
                            Id = new Guid("2a0a0001-0000-4000-8000-000000000022"),
                            BestTimeToVisit = "May-October",
                            Description = "Jajce is the only town in the world with a waterfall right at its center — the Pliva plunges roughly 20 meters into the Vrbas, just below the medieval fortress that was once the last stronghold of the independent Bosnian Kingdom. In 1943 the town hosted the second AVNOJ session, which laid the foundation for socialist Yugoslavia. A few kilometers upstream, old watermills on the Pliva Lakes (\"mlinčići\") add another layer to this small but historically rich town.",
                            DestinationId = new Guid("1a0a0001-0000-4000-8000-000000000011"),
                            LanguageCode = "en"
                        });
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountKM")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Expense", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.ItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripDayId", "Order")
                        .IsUnique();

                    b.ToTable("ItineraryItem", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Travelers")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.TripDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDay", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Preferences")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.WeatherSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("WeatherSnapshot", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Destination", "Destination")
                        .WithMany("Accommodations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.DestinationTranslation", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Destination", "Destination")
                        .WithMany("Translations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Expense", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.ItineraryItem", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Place", "Place")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlanner.Api.Domain.Entities.TripDay", "TripDay")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("TripDay");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Place", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Destination", "Destination")
                        .WithMany("Places")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Trip", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.TripDay", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Trip", "Trip")
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.WeatherSnapshot", b =>
                {
                    b.HasOne("TravelPlanner.Api.Domain.Entities.Destination", "Destination")
                        .WithMany("WeatherSnapshots")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Places");

                    b.Navigation("Translations");

                    b.Navigation("WeatherSnapshots");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Place", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.TripDay", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("TravelPlanner.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
