export type Language = "bs" | "en";
export const LANGUAGE_COOKIE = "travelPlanner.language";
export const getLanguage = (value: string | undefined): Language => value === "en" ? "en" : "bs";

const tagTranslations: Record<string, Record<Language, string>> = {
  historija: { bs: "Historija", en: "History" }, kultura: { bs: "Kultura", en: "Culture" }, priroda: { bs: "Priroda", en: "Nature" }, planina: { bs: "Planina", en: "Mountain" }, avantura: { bs: "Avantura", en: "Adventure" }, hrana: { bs: "Hrana", en: "Food" }, vino: { bs: "Vino", en: "Wine" }, rijeka: { bs: "Rijeka", en: "River" }, grad: { bs: "Grad", en: "City" }, more: { bs: "More", en: "Sea" }, porodica: { bs: "Porodica", en: "Family" }, wellness: { bs: "Wellness", en: "Wellness" }, zima: { bs: "Zima", en: "Winter" },
};
export function formatTagLabel(tag: string, language: Language) { const label = tagTranslations[tag.toLocaleLowerCase("bs")]?.[language] ?? tag; return `${label.charAt(0).toLocaleLowerCase(language)}${label.slice(1)}`; }
export function formatTag(tag: string, language: Language) { const label = formatTagLabel(tag, language); return `#${label.charAt(0).toLocaleUpperCase(language)}${label.slice(1)}`; }

export const text = {
  bs: {
    home: { skip: "Preskoči na sadržaj", nav: "Glavna navigacija", how: "Kako funkcioniše", login: "Prijava", register: "Kreiraj račun", hero: ["Blizu je.", "A toliko toga", "tek treba otkriti."], heroDescription: "Upoznaj Bosnu i Hercegovinu svojim tempom. Pronađi mjesta za sebe, od čaršijskih ulica do planinskih staza.", findTrip: "Pronađi svoje putovanje", heroNote: "Tvoja interesovanja. Tvoj budžet. Tvoj ritam.", photoAlt: "Stari most preko Neretve, kamene kuće Mostara i brdo u pozadini", photoCaption: "Fotografija: Yu Siang Teo · Unsplash", sectionNumber: "01 — PO TVOJOJ MJERI", introTitle: ["Dobar početak", "svakog putovanja."], introDescription: ["Ne moraš znati odakle krenuti.", "Kreni od onoga što voliš."], steps: [["Reci nam šta te privlači", "Historija, priroda, hrana ili malo od svega. Odaberi interesovanja, budžet i vrijeme za putovanje."], ["Otkrij mjesta koja ti odgovaraju", "Dobij preporuke iz našeg izbora BiH destinacija, uz objašnjenje zašto bi ti se mogle svidjeti."], ["Pronađi svoj sljedeći pravac", "Uporedi preporuke i promijeni odabir kad poželiš drugačiji doživljaj."]], closing: ["Od Sarajeva do Trebinja.", "Počni od znatiželje."], startExploring: "Počni istraživati", footer: "Putovanja počinju bliže nego što misliš.", existingAccount: "Već imaš račun? Prijavi se" },
    auth: { loginTitle: "Dobro došao nazad", registerTitle: "Kreiraj svoj račun", loginDescription: "Prijavi se da nastaviš s planiranjem putovanja.", registerDescription: "Sačuvaj svoja interesovanja i pronađi putovanje po svojoj mjeri.", displayName: "Ime za prikaz", password: "Lozinka", login: "Prijavi se", register: "Registruj se", submitting: "Molimo sačekaj…", hasAccount: "Već imaš račun?", noAccount: "Nemaš račun?", loginFailed: "Prijava nije uspjela.", unexpectedError: "Došlo je do greške." },
    rec: { loadingProfile: "Učitavamo tvoj profil…", expired: "Sesija je istekla. Prijavi se ponovo.", profileUnavailable: "Profil nije dostupan.", interestsSaveFailed: "Interesovanja nisu sačuvana.", unavailable: "Preporuke nisu dostupne.", logout: "Odjavi se", title: ["Gdje te vodi", "znatiželja?"], description: "Reci nam šta voliš. Pronađimo tvoj sljedeći kutak Bosne i Hercegovine.", interestsTitle: "Šta želiš doživjeti?", interestsHint: "Odaberi sve što te privlači.", budget: "Tvoj budžet", budgetHint: "Okvirni nivo troška, bez iznosa u KM.", days: "Koliko dana imaš?", daysHint: "Od kratkog predaha do dužeg odmora.", daysUnit: "dana", season: "Kada putuješ?", seasonHint: "Svako godišnje doba ima svoj doživljaj.", saved: ["Interesovanja čuvamo na tvom profilu.", "Odabir možeš promijeniti kad god poželiš."], find: "Prikaži preporuke", finding: "Tražimo preporuke…", loading: "Učitavanje preporuka…", shown: (count: number) => `Prikazano preporuka: ${count}.`, resultsTitle: "Mjesta za tvoj ritam.", resultsDescription: "Tvoje preporuke, poredane prema odabranim preferencijama.", map: "Otvori mapu", why: "Zašto ti odgovara", about: "Više o destinaciji", bestTime: "Najbolje vrijeme za posjetu: ", points: "bodova", recommendationReason: { prefix: "Odgovara", fallback: "Kurirana početna preporuka za tvoje putovanje.", interests: (tags: string) => `tvojim interesovanjima (${tags})`, season: "odabranoj sezoni", budget: "budžetu", duration: "trajanju putovanja", conjunction: "i", usesSerialComma: false }, empty: ["Prvo tvoja interesovanja.", "Zatim mjesta koja vrijedi upoznati."], interestOptions: [["historija", "Historija"], ["kultura", "Kultura"], ["priroda", "Priroda"], ["planina", "Planina"], ["avantura", "Avantura"], ["hrana", "Hrana"], ["vino", "Vino"], ["rijeka", "Rijeka"]], budgets: [["budget", "Niži"], ["standard", "Srednji"], ["premium", "Viši"]], seasons: [["spring", "Proljeće"], ["summer", "Ljeto"], ["autumn", "Jesen"], ["winter", "Zima"]] },
    destination: { home: "Početna", recommendations: "Preporuke", country: "Bosna i Hercegovina", stay: "Vrijeme za istraživanje", days: "dana", bestTime: "Najbolje vrijeme za posjetu", mapAction: "Istraži na mapi", overview: "Upoznaj", mapTitle: "Mjesta u blizini", mapIntro: "Pronađi svoj sljedeći korak.", continue: "Nastavi istraživati ↗", breadcrumb: "Putanja", interests: "Interesovanja", photoAlt: "Stari most iznad Neretve i kamene kuće Mostara", photoCaption: "Mostar na Neretvi · Fotografija: Yu Siang Teo / Unsplash", mapUnavailable: "Mapa trenutno nije dostupna.", mapFallback: "Mjesta možeš pregledati u listi uz mapu.", retry: "Pokušaj ponovo", mapLoading: "Učitavamo mapu…", mapDestination: "Destinacija", nearby: "Obližnja mjesta", around: "Oko tebe", noPlaces: "Za ovu destinaciju još nema dodanih obližnjih mjesta. Na mapi je označena sama destinacija.", loading: "Učitavamo destinaciju…", missingTitle: "Destinacija nije pronađena.", missingText: "Provjeri adresu ili pronađi novo mjesto među preporukama.", explore: "Istraži preporuke", errorTitle: "Destinaciju trenutno ne možemo učitati.", errorText: "Pokušaj ponovo za nekoliko trenutaka." },
  },
  en: {
    home: { skip: "Skip to content", nav: "Main navigation", how: "How it works", login: "Log in", register: "Create account", hero: ["So close.", "And so much", "left to discover."], heroDescription: "Explore Bosnia and Herzegovina at your own pace. Find places that suit you, from old-town lanes to mountain trails.", findTrip: "Find your trip", heroNote: "Your interests. Your budget. Your pace.", photoAlt: "Stari Most over the Neretva, Mostar's stone houses and the hillside beyond", photoCaption: "Photo: Yu Siang Teo · Unsplash", sectionNumber: "01 — TAILORED TO YOU", introTitle: ["A good beginning", "for every trip."], introDescription: ["You do not need to know where to start.", "Start with what you love."], steps: [["Tell us what draws you in", "History, nature, food, or a little of everything. Choose your interests, budget, and travel dates."], ["Discover places that suit you", "Get recommendations from our curated selection of BiH destinations, with an explanation of why they may fit you."], ["Find your next direction", "Compare recommendations and change your choices whenever you want a different experience."]], closing: ["From Sarajevo to Trebinje.", "Begin with curiosity."], startExploring: "Start exploring", footer: "Trips begin closer than you think.", existingAccount: "Already have an account? Log in" },
    auth: { loginTitle: "Welcome back", registerTitle: "Create your account", loginDescription: "Log in to continue planning your trip.", registerDescription: "Save your interests and find a trip made for you.", displayName: "Display name", password: "Password", login: "Log in", register: "Register", submitting: "Please wait…", hasAccount: "Already have an account?", noAccount: "Don't have an account?", loginFailed: "Unable to sign in.", unexpectedError: "Something went wrong." },
    rec: { loadingProfile: "Loading your profile…", expired: "Your session has expired. Please log in again.", profileUnavailable: "Your profile is unavailable.", interestsSaveFailed: "Your interests could not be saved.", unavailable: "Recommendations are unavailable.", logout: "Log out", title: ["Where does", "curiosity take you?"], description: "Tell us what you love. Let’s find your next corner of Bosnia and Herzegovina.", interestsTitle: "What would you like to experience?", interestsHint: "Choose everything that appeals to you.", budget: "Your budget", budgetHint: "An approximate spending level, without BAM amounts.", days: "How many days do you have?", daysHint: "From a short break to a longer holiday.", daysUnit: "days", season: "When are you travelling?", seasonHint: "Every season has its own experience.", saved: ["We save interests to your profile.", "You can change your choices whenever you want."], find: "Show recommendations", finding: "Finding recommendations…", loading: "Loading recommendations…", shown: (count: number) => `Recommendations shown: ${count}.`, resultsTitle: "Places for your pace.", resultsDescription: "Your recommendations, ranked by the preferences you selected.", map: "Open map", why: "Why it fits", about: "About this destination", bestTime: "Best time to visit: ", points: "points", recommendationReason: { prefix: "It suits", fallback: "A curated starting suggestion for your trip.", interests: (tags: string) => `your interests (${tags})`, season: "the selected season", budget: "your budget", duration: "your trip length", conjunction: "and", usesSerialComma: true }, empty: ["First, your interests.", "Then, places worth getting to know."], interestOptions: [["historija", "History"], ["kultura", "Culture"], ["priroda", "Nature"], ["planina", "Mountain"], ["avantura", "Adventure"], ["hrana", "Food"], ["vino", "Wine"], ["rijeka", "River"]], budgets: [["budget", "Lower"], ["standard", "Medium"], ["premium", "Higher"]], seasons: [["spring", "Spring"], ["summer", "Summer"], ["autumn", "Autumn"], ["winter", "Winter"]] },
    destination: { home: "Home", recommendations: "Recommendations", country: "Bosnia and Herzegovina", stay: "Time to explore", days: "days", bestTime: "Best time to visit", mapAction: "Explore on map", overview: "Discover", mapTitle: "Nearby places", mapIntro: "Find your next stop.", continue: "Keep exploring ↗", breadcrumb: "Breadcrumb", interests: "Interests", photoAlt: "Stari Most above the Neretva and Mostar's stone houses", photoCaption: "Mostar on the Neretva · Photo: Yu Siang Teo / Unsplash", mapUnavailable: "The map is currently unavailable.", mapFallback: "You can browse places in the list beside the map.", retry: "Try again", mapLoading: "Loading map…", mapDestination: "Destination", nearby: "Nearby places", around: "Around you", noPlaces: "There are no nearby places for this destination yet. The destination itself is marked on the map.", loading: "Loading destination…", missingTitle: "Destination not found.", missingText: "Check the address or find a new place in the recommendations.", explore: "Explore recommendations", errorTitle: "We cannot load this destination right now.", errorText: "Try again in a moment." },
  },
} as const;
